-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/qpqawljyrspucqfivzge/sql

-- ===== MIGRATION: Fix contact_submissions policies =====
drop policy if exists "Allow service role to read all" on contact_submissions;
drop policy if exists "Allow anonymous inserts" on contact_submissions;
drop policy if exists "Allow authenticated reads" on contact_submissions;
drop policy if exists "Allow authenticated deletes" on contact_submissions;

create policy "Allow anonymous inserts"
  on contact_submissions
  for insert
  to anon
  with check (true);

create policy "Allow authenticated reads"
  on contact_submissions
  for select
  to authenticated
  using (true);

create policy "Allow authenticated deletes"
  on contact_submissions
  for delete
  to authenticated
  using (true);

-- ===== templates table =====
create table if not exists templates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  name text not null,
  description text not null,
  image_url text,
  category text not null,
  icon_name text not null default 'Home',
  gradient_from text not null default 'sky-500',
  gradient_to text not null default 'blue-600',
  preview_gradient text not null default 'from-sky-400 via-blue-500 to-indigo-600',
  sort_order integer default 0,
  url text
);

alter table templates enable row level security;

drop policy if exists "Allow public reads" on templates;
drop policy if exists "Allow authenticated inserts" on templates;
drop policy if exists "Allow authenticated updates" on templates;
drop policy if exists "Allow authenticated deletes" on templates;

create policy "Allow public reads"
  on templates
  for select
  to anon, authenticated
  using (true);

create policy "Allow authenticated inserts"
  on templates
  for insert
  to authenticated
  with check (true);

create policy "Allow authenticated updates"
  on templates
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Allow authenticated deletes"
  on templates
  for delete
  to authenticated
  using (true);

-- ===== Migration: add url column to existing templates table =====
alter table templates add column if not exists url text;

-- ===== Migration: add phone, status, remarks columns to contact_submissions =====
alter table contact_submissions add column if not exists phone text;
alter table contact_submissions add column if not exists status text default 'new';
alter table contact_submissions add column if not exists remarks text;

-- ===== Migration: add budget, timeline columns to contact_submissions =====
alter table contact_submissions add column if not exists budget text;
alter table contact_submissions add column if not exists timeline text;

-- ===== invoices table =====
create table if not exists invoices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  client_name text not null,
  client_email text not null,
  client_phone text,
  service text not null,
  description text,
  amount numeric not null,
  vat_rate numeric not null default 16,
  vat_amount numeric not null,
  total numeric not null,
  invoice_number text not null unique,
  status text default 'pending'
);

-- ===== Migration: add payment detail columns to invoices =====
alter table invoices add column if not exists payment_bank text;
alter table invoices add column if not exists payment_account_name text;
alter table invoices add column if not exists payment_account_number text;
alter table invoices add column if not exists payment_branch text;

alter table invoices enable row level security;

drop policy if exists "Allow authenticated all" on invoices;
create policy "Allow authenticated all"
  on invoices
  for all
  to authenticated
  using (true)
  with check (true);

-- ===== Storage bucket for template images =====
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('templates', 'templates', true, 5242880, array['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
on conflict (id) do nothing;

-- Allow authenticated users to upload
drop policy if exists "Allow authenticated uploads" on storage.objects;
create policy "Allow authenticated uploads"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'templates');

-- Allow public to view
drop policy if exists "Allow public to view templates" on storage.objects;
create policy "Allow public to view templates"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'templates');

-- Allow authenticated to delete
drop policy if exists "Allow authenticated deletes on templates" on storage.objects;
create policy "Allow authenticated deletes on templates"
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'templates');

-- ===== blog_posts table =====
create table if not exists blog_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  slug text not null unique,
  title text not null,
  excerpt text,
  content text,
  cover_image_url text,
  author text default 'Pigiecore Solutions',
  published boolean default false,
  published_at timestamp with time zone
);

alter table blog_posts enable row level security;

drop policy if exists "Public read published blog posts" on blog_posts;
create policy "Public read published blog posts"
  on blog_posts
  for select
  to anon, authenticated
  using (published = true);

drop policy if exists "Allow authenticated all on blog_posts" on blog_posts;
create policy "Allow authenticated all on blog_posts"
  on blog_posts
  for all
  to authenticated
  using (true)
  with check (true);

-- ===== testimonials table =====
create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  client_name text not null,
  company text,
  role text,
  content text not null,
  rating smallint not null default 5,
  avatar_url text,
  published boolean default true,
  sort_order integer default 0
);

alter table testimonials enable row level security;

drop policy if exists "Public read published testimonials" on testimonials;
create policy "Public read published testimonials"
  on testimonials
  for select
  to anon, authenticated
  using (published = true);

drop policy if exists "Allow authenticated all on testimonials" on testimonials;
create policy "Allow authenticated all on testimonials"
  on testimonials
  for all
  to authenticated
  using (true)
  with check (true);

-- ===== offers table =====
create table if not exists offers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  title text not null,
  body text,
  button_text text,
  button_url text,
  color_from text default '#2563eb',
  color_to text default '#9333ea',
  active boolean default true,
  sort_order integer default 0
);

alter table offers enable row level security;

drop policy if exists "Public read active offers" on offers;
create policy "Public read active offers"
  on offers
  for select
  to anon, authenticated
  using (active = true);

drop policy if exists "Allow authenticated all on offers" on offers;
create policy "Allow authenticated all on offers"
  on offers
  for all
  to authenticated
  using (true)
  with check (true);

-- ===== Company settings (single row used on invoices & quotations) =====
create table if not exists company_settings (
  id integer primary key default 1,
  company_name text default 'Pigiecore Solutions',
  email text,
  phone text,
  alt_phone text,
  address text,
  website text,
  tax_pin text,
  logo_url text,
  bank_name text,
  bank_account_name text,
  bank_account_number text,
  bank_branch text,
  invoice_prefix text default 'PINV',
  quote_prefix text default 'PQT',
  notes text,
  updated_at timestamptz default now()
);

insert into company_settings (id) values (1) on conflict (id) do nothing;

alter table company_settings enable row level security;
drop policy if exists "Allow authenticated all on company_settings" on company_settings;
create policy "Allow authenticated all on company_settings"
on company_settings for all to authenticated using (true) with check (true);

-- ===== quotations table =====
create table if not exists quotations (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  client_name text not null,
  client_email text not null,
  client_phone text,
  service text not null,
  description text,
  amount numeric not null default 0,
  vat_rate numeric default 16,
  vat_amount numeric default 0,
  total numeric default 0,
  quote_number text not null,
  valid_until date,
  status text default 'draft',
  payment_bank text,
  payment_account_name text,
  payment_account_number text,
  payment_branch text
);

alter table quotations enable row level security;
drop policy if exists "Allow authenticated all on quotations" on quotations;
create policy "Allow authenticated all on quotations"
on quotations for all to authenticated using (true) with check (true);
